services:
  - type: web
    name: user-management-backend
    env: python
    plan: free
    buildCommand: |
      python backend/manage.py migrate --noinput
    startCommand: gunicorn backend.wsgi:application
