services:
  - type: web
    name: user-management-backend
    env: python
    plan: free
    buildCommand: python manage.py migrate --noinput --verbosity 3
    startCommand: gunicorn backend.wsgi:application
